using Pkg

Pkg.activate(".")
Pkg.add("BlackBoxOptimizationBenchmarking")
Pkg.add("Distributions")
Pkg.add("JSON")
Pkg.add("Parameters")
Pkg.add("Shuffle")
Pkg.add("StatsBase")
Pkg.add("Plots")
Pkg.add("DataFrames")
Pkg.add("CSV")
Pkg.add("StatsPlots")
Pkg.add("Cairo")
Pkg.add("Fontconfig")
Pkg.add("Gadfly")
Pkg.add("Distances")
Pkg.add("InformationMeasures")
